{{- if .Values.httproute.enabled -}}
{{- $servicePort := .Values.service.port -}}
{{- $fullName := include "zigbee2mqtt.fullname" . }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
    {{- with .Values.httproute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- range . }}
    - group: {{ .group | default "gateway.networking.k8s.io" }}
      kind: {{ .kind | default "Gateway" }}
      name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: {{ .Values.httproute.pathType | default "PathPrefix" }}
        value: {{ .Values.httproute.path | default "/" }}
    backendRefs:
    - name: {{ $fullName }}
      port: {{ $servicePort }}
{{- end }}
